### ISSUE TITLE
v2.3.6 DFP X button dismisses the ad AND the parent view controller.

### ISSUE THREAD

**Issue by edalford11** [sharethrough/iOS-SDK#24]
Just upgraded to 2.3.6 and now when I tap a UITableViewCell that is an ad cell, the ad will pop up but after tapping the X button, it dismisses the ad then dismisses my entire view controller. I have checked my code to be sure it is not a bug on my end and there is nothing that would cause this to happen on my end. Please advise.

Using 2.3.5 for now as this isn't an issue in that version.

**Comment by edalford11** [comment]
Scratch that. I can't use 2.3.5 either because when I call 

[[SharethroughSDKDFP sharedInstance] prefetchAdForPlacementKey:kAdsPlacementKey delegate:self];

I get a retain cycle and my view controller never gets released from memory after it is dismissed. What's going on?

**Comment by nuclearghost** [comment]
I've got a fix for the retain cycle @edalford11 , but want to double check this dismissal issue as well. Can you tell me what your ViewController set up is. Do you have a modally presented view controller that's showing Sharethrough Ads, then when the Sharethrough Ad view controller is dismissed, it's also dismissing your presented controller?

**Comment by edalford11** [comment]
Thanks @nuclearghost. So the UITableViewController that contains the ads is part of a navigation controller stack, which is inside of a UITabBarController. When tapping on the ad cell, the ad is presented but when tapping the x, the ad gets dismissed and then the entire UITabBarController gets dismissed after that.

**Comment by nuclearghost** [comment]
Got it. I'll build a sample to reproduce and fix this before cutting a release. Thanks for the info @edalford11

**Comment by nuclearghost** [comment]
Hey @edalford11 can you check out the new 2.3.8 release and let me know if it fixes the retain cycle as well as the dismissal issue. Thanks! 

https://github.com/sharethrough/iOS-SDK/releases/tag/v2.3.8

**Comment by edalford11** [comment]
Hey @nuclearghost it looks like the retain cycle is still happening. Also this new release is now failing to load all of my ads so I wasn't able to confirm that the X button was working properly. When going back to version 2.3.5, all of my ads were loading properly.

**Comment by nuclearghost** [comment]
Hi @edalford11 I've been working to track down the retain cycle but not having much luck. I created a simple repo that just does the prefetch and it has a singleton delegate. I would expect the retain count on the delegate to be +2 (it should be +1 because of the singleton), but this doesn't appear to be the case. 

Can you please modify this app to replicate what you're seeing? 

https://github.com/nuclearghost/single-str-view

**Comment by edalford11** [comment]
@nuclearghost we are using the dfp version. After swapping it out for the dfp version, the retain cycle immediately popped up. https://github.com/nuclearghost/single-str-view/pull/2

**Comment by nuclearghost** [comment]
@edalford11 thanks for your assistance. Can you please try out version 2.3.9 and confirm it fixes your issues? https://github.com/sharethrough/iOS-SDK/releases/tag/v2.3.9

**Comment by edalford11** [comment]
@nuclearghost looks like the retain cycle is fixed but still having the same issue where now all of the sudden the ads don't load in the table. I've confirmed that putting back in version 2.3.5, the ads load properly but by putting back in the new release, the ads don't load.

**Comment by nuclearghost** [comment]
I did have to make some changes to remove the retain cycle, but confirmed I was seeing ads through DFP. Can you let me know what placement key you're using?

**Comment by nuclearghost** [comment]
Also @edalford11 can you try testing with the placement key "e7244b42" and see if you get an ad. That one should always return one from DFP

**Comment by edalford11** [comment]
@nuclearghost I'm using placement key "f8b11995". I've tried using the test placement key you gave but I get the same result. On 2.3.5, all works fine but on the new release, neither 

- (void)adView:(id<STRAdView>)adView didFetchAdForPlacementKey:(NSString *)placementKey atIndex:(NSInteger)adIndex

or

- (void)adView:(id<STRAdView>)adView didFailToFetchAdForPlacementKey:(NSString *)placementKey atIndex:(NSInteger)adIndex

get called.

**Comment by nuclearghost** [comment]
@edalford11 ah that's bad documentation on my part. It actually calls a new method when it succeeds. I'm sorry for the confusion. Here's the new method. I tested with your placement key and I received ads back

```
/**
 * Delegate is notified of a successful prefetch with the ad
 *
 * @param strAd     The advertisement received during the prefetch, or the first ad if there are multiple ads.
 */
- (void)didPrefetchAdvertisement:(STRAdvertisement *)strAd;
```

**Comment by edalford11** [comment]
@nuclearghost it is essential that I get a hold of the STRAdView from the original delegate method after fetch. This new delegate method is passing in an STRAdvertisement and I don't know what that is and I don't see any documentation on it. 

I was using the adView to cast it to my subclassed ad cell like so

_adCell = (STSAdNewsFeedCell*)strAd;

How would I be able to do this with STRAdvertisement?

**Comment by nuclearghost** [comment]
@edalford11 understood. So the prefetch method will just come back to let you know ads are available. Then when you actually call the `placeAdInView` method you'll still get the view back like you need. Will that work for you?

**Comment by edalford11** [comment]
@nuclearghost it won't. I don't know if you remember speaking with me about this when initially making this integration but it was essential that I was able to access to the ads data so I can calculate the ad cell height in heightForRowAtIndexPath so the ad cell can be displayed nicely with the right height. Keeping track of the _adCell being returned from the delegate method was how I was able to do this.

**Comment by nuclearghost** [comment]
@edalford11 ah yes I do recall. Let me explain the flow a little better:

Your app calls `prefetchAdForPlacementKey:delegate:`
If successful, the delegate's `didPrefetchAdvertisement:` method will be called. At this time you know ads are available.
When you get to the point where you need to place an ad in a cell, your app calls `placeAdInView:placementKey: dfpPath:presentingViewController:delegate:`
When this is successful, the delegate's `adView:adView didFetchAdForPlacementKey:atIndex:` will be called and you'll have access to the ad view and can resize it as needed

If at any point the prefetch or placing an ad into a view fails, the delegate's `adView:didFailToFetchAdForPlacementKey:atIndex:` will be called so your app is notified of the failure.

Does that make sense?

**Comment by edalford11** [comment]
@nuclearghost it does and I've implemented it this way but what happens is didPrefetchAdvertisement gets called but adView:adView didFetchAdForPlacementKey:atIndex: is never called after that. So what I end up with is an ad in a cell with a 0 height.

**Comment by nuclearghost** [comment]
@edalford11 got it. Let me look into it. Sorry for all the confusion

**Comment by nuclearghost** [comment]
Ah sorry another documentation issue. The delegate call has changed to 

`- (void)adView:(id<STRAdView>)adView didFetchAd:(STRAdvertisement*)ad ForPlacementKey:(NSString *)placementKey atIndex:(NSInteger)adIndex;`

Can you let me know if that works?

We're working on major overhauls of our release process and documentation in 2016 to alleviate issues like this.

**Comment by edalford11** [comment]
That was it. Thanks for the help @nuclearghost.

**Comment by nuclearghost** [comment]
Excellent. Sorry again for the confusion @edalford11
