### ISSUE TITLE
Nil STRAdvertisement on didPrefetchAdvertisement

### ISSUE THREAD

**Issue by cthomaschase** [sharethrough/iOS-SDK#27]
Hi,

We've upgraded to SDK 3.0. I'm seeing cases where

```- (void)didPrefetchAdvertisement:(STRAdvertisement *)strAd``` will sometimes return with a nil ```strAd``` object.

Is this the expected behavior (as opposed to calling ```- (void)didFailToPrefetchForPlacementKey:(NSString *)placementKey)```?

**Comment by nuclearghost** [comment]
Hi @cthomaschase can you tell me if this was using the version of the SDK that communicates with DFP?

**Comment by cthomaschase** [comment]
We are not using the DFP version.

**Comment by nuclearghost** [comment]
Hi @cthomaschase please check out the new v3.2.3 release which should address this issue. https://github.com/sharethrough/iOS-SDK/releases/tag/v3.2.3
