### ISSUE TITLE
Implementation Best Practices

### ISSUE THREAD

**Issue by cthomaschase** [sharethrough/iOS-SDK#28]
I've read the documentation many times and have the SDK implemented in our app for while now. I'm looking to get clarification and certainty that we've implemented correctly. A few open questions:

1. Is `prefetchAdForPlacementKey:(NSString *)placementKey delegate (id<STRAdViewDelegate>)delegate` intended to be used once on app initialization or is it ok to call this each time we make a request for an ad?

2. When is `isAdAvailableForPlacement:(NSString *)placementKey atIndex:(NSInteger)index` intended to be called? Are we to call this before we fetch or prefetch?

3. If we call `isAdAvailableForPlacement:(NSString *)placementKey atIndex:(NSInteger)index` before inserting an ad via `placeAdInView:(UIView<STRAdView> *)view placementKey:(NSString *)placementKey presentingViewController:(UIViewController *)presentingViewController index:(NSInteger)index delegate:(id<STRAdViewDelegate>)delegate`, are we to assume that if the result is **true** we DO NOT need to monitor the delegate for `adView:(id<STRAdView>)adView didFailToFetchAdForPlacementKey:(NSString *)placementKey atIndex:(NSInteger)adIndex`?

Thanks!

**Comment by cthomaschase** [comment]
@nuclearghost could you please comment on this?

**Comment by nuclearghost** [comment]
@cthomaschase my apologies for the delay.

1) It's only necessary to call this to prime the cache. The SDK will automatically request ads when the cache is getting low on ads.

2) This should be called when attempting to place an ad in view through the Basic API. This guarantees that an ad is available before actually attempting to render the ad.

3) That's a correct assumption! If you know an ad is available, we'll definitely be able to successfully render it.

**Comment by cthomaschase** [comment]
@nuclearghost no worries.

1) Does the API request and cache multiple ads behind the scenes? If so, does that count as multiple "Impression Requests" via your dashboard? For instance, if we prefetch once, would we potentially have more than one Impression Request logged to the dashboard?

**Comment by nuclearghost** [comment]
1) That's correct it does manage this automatically. Each Impression Request can actually return up to 5 creatives to cut down on network traffic

**Comment by cthomaschase** [comment]
If one impression request returns 5 ads, is that still only considered one request via the dashboard, or 5?

**Comment by nuclearghost** [comment]
It would count as 1 Impression Request and 5 Impressions

**Comment by cthomaschase** [comment]
Great, thank you.
