### ISSUE TITLE
Ads appearing only for few seconds

### ISSUE THREAD

**Issue by RD1991** [sharethrough/iOS-SDK#29]
Hi There, 

The full explanation of the question is on this `[stackover flow link](http://stackoverflow.com/questions/36693379/iphone-and-ipad-ads-appears-only-for-few-seconds-and-then-disapperas
)`. Can you please help us to resolve this error?

**Comment by nuclearghost** [comment]
Hey @RD1991 probably best to transfer all the details here from SO and close that question. Don't think anyone will be able to help except me :) 

Can you tell me more about the containerView that you're placing the ad in. Does that have any refresh on it? Perhaps could you share that whole class?

You won't be able to use different versions of the SDK as the namespace will conflict.

**Comment by RD1991** [comment]
Hi Mark,

Thank you for your response, we are facing the issue of disappearing ads
after few seconds. We are sharing the video of the same with this mail.
We have integrated sharethroughSDK
<https://github.com/sharethrough/iOS-SDK/releases>.DFP.Integration v3.2.3
(Sharethrough+DFP) in our iOS application which runs on both iPhone and
iPad. We placed the ad using following statement,

[[SharethroughSDKDFP sharedInstance] placeAdInView:(UIView<STRAdView>
*)self.containerView placementKey:_adUnit dfpPath:(_subAdUnit.length ?
_subAdUnit : nil) presentingViewController:self.presentingController index:0
delegate:self];

Please let us know if you need clarification.

We need to fix this issue asap.
Please find the class which places the Ad, iPad log and video of the issue
attached herewith.

​
 IMG_0003.MOV
<https://drive.google.com/a/afourtech.com/file/d/0BxdATWqFJ51Dc0M5YTZRZ2RWTkU/view?usp=drive_web>
​




On Mon, Apr 18, 2016 at 8:35 PM, Rajesh Darak <rajeshdarak1991@gmail.com>
wrote:

> Please check whole mail and try to reply the guy.
>
> Rajesh Darak
>
> Begin forwarded message:
>
> *From:* Mark Meyer <notifications@github.com>
> *Date:* 18 April 2016 at 7:55:19 PM IST
> *To:* sharethrough/iOS-SDK <iOS-SDK@noreply.github.com>
> *Cc:* Rajesh Darak <rajeshdarak1991@gmail.com>
> *Subject:* *Re: [sharethrough/iOS-SDK] Ads appearing only for few seconds
> (#29)*
> *Reply-To:* sharethrough/iOS-SDK <
> reply@reply.github.com
> >
>
> Hey @RD1991 <https://github.com/RD1991> probably best to transfer all the
> details here from SO and close that question. Don't think anyone will be
> able to help except me :)
>
> Can you tell me more about the containerView that you're placing the ad
> in. Does that have any refresh on it? Perhaps could you share that whole
> class?
>
> You won't be able to use different versions of the SDK as the namespace
> will conflict.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sharethrough/iOS-SDK/issues/29#issuecomment-211402767>
>
>


-- 
Regards,

Milind Joshi.

-- 
DISCLAIMER ========== This e-mail may contain privileged and confidential 
information which is the property of AFour Technologies Pvt. Ltd. It is 
intended only for the use of the individual or entity to which it is 
addressed. If you are not the intended recipient, you are not authorized to 
read, retain, copy, print, distribute or use this message. If you have 
received this communication in error, please notify the sender and delete 
all copies of this message. AFour Technologies Pvt. Ltd. does not accept 
any liability for virus infected mails.

**Comment by nuclearghost** [comment]
Definitely want to help get this resolved. 

Can you provide any more information about the class where you're placing the ad or the collection view the ads are placed in?

**Comment by milindjoshi297** [comment]
Sure. I am sharing the class here.


[Archive 2.zip](https://github.com/sharethrough/iOS-SDK/files/225308/Archive.2.zip)

**Comment by milindjoshi297** [comment]
Hi @nuclearghost 

Can you please provide us your gmail id? We want to share the video of the issue which @RD1991 shared yesterday with you, but it can only be shared to gmail accounts. So please provide us your gmail id to share the video as well to get better understanding of the problem we are facing.
Thank you.

**Comment by nuclearghost** [comment]
Hi @milindjoshi297 you can send the video to ios@sharethrough.com

I'll review the class you shared

**Comment by milindjoshi297** [comment]
Hi Mark,

We shared the video on your email id provided, please check if you can
access it.

On Tue, Apr 19, 2016 at 7:41 PM, Mark Meyer <notifications@github.com>
wrote:

> Hi @milindjoshi297 <https://github.com/milindjoshi297> you can send the
> video to ios@sharethrough.com
>
> I'll review the class you shared
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sharethrough/iOS-SDK/issues/29#issuecomment-211938069>
>



-- 
Regards,

Milind Joshi.

-- 
DISCLAIMER ========== This e-mail may contain privileged and confidential 
information which is the property of AFour Technologies Pvt. Ltd. It is 
intended only for the use of the individual or entity to which it is 
addressed. If you are not the intended recipient, you are not authorized to 
read, retain, copy, print, distribute or use this message. If you have 
received this communication in error, please notify the sender and delete 
all copies of this message. AFour Technologies Pvt. Ltd. does not accept 
any liability for virus infected mails.

**Comment by nuclearghost** [comment]
Hi @milindjoshi297 I can now access the video and see what you're saying. The class you've provided does not actually make any calls to the SharethroughSDK, can you provide the class where those calls are made as well?

**Comment by milindjoshi297** [comment]
Hi Mark,

We have provided you HTAdCacheManager class in previous mails from where we
are actually calling

[[SharethroughSDKDFP sharedInstance] placeAdInView:(UIView<STRAdView>
*)self.containerView placementKey:_adUnit dfpPath:(_subAdUnit.length ?
_subAdUnit : nil) presentingViewController:self.presentingController
index:0 delegate:self];
method to place the ads. This class is generic class to show the ads. We
are sharing the class with this mail too. Please check the class files
attached herewith.

And, HTHMFeturedViewController class is actually calling HTADCacheManager's
method to show the Ads. So "HTHMFeturedViewController" is a view controller
and "HTAdCacheManager" has the actual code to handle Ads. We are sharing
the class with this mail too. Please check the class files attached
herewith.

Please let us know if you need more clarification on this.
Thank you.



On Tue, Apr 19, 2016 at 8:46 PM, Mark Meyer <notifications@github.com>
wrote:

> Hi @milindjoshi297 <https://github.com/milindjoshi297> I can now access
> the video and see what you're saying. The class you've provided does not
> actually make any calls to the SharethroughSDK, can you provide the class
> where those calls are made as well?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sharethrough/iOS-SDK/issues/29#issuecomment-211974251>
>



-- 
Regards,

Milind Joshi.

-- 
DISCLAIMER ========== This e-mail may contain privileged and confidential 
information which is the property of AFour Technologies Pvt. Ltd. It is 
intended only for the use of the individual or entity to which it is 
addressed. If you are not the intended recipient, you are not authorized to 
read, retain, copy, print, distribute or use this message. If you have 
received this communication in error, please notify the sender and delete 
all copies of this message. AFour Technologies Pvt. Ltd. does not accept 
any liability for virus infected mails.

**Comment by nuclearghost** [comment]
Hi @milindjoshi297 can you please send all the files to ios@sharethrough.com , the attachments are falling off on the GitHub issue

**Comment by milindjoshi297** [comment]
@nuclearghost We sent all the files to ios@sharethrough.com , Please check now.

**Comment by nuclearghost** [comment]
@milindjoshi297 received. I'll review the code provided. Thanks!

**Comment by milindjoshi297** [comment]
Thanks @nuclearghost This is an issue with highest priority and we need to fix this issue on urgent basis.

**Comment by nuclearghost** [comment]
Hi @milindjoshi297 

I see now that you're doing lots of things with GCD in your code. The SDK is usually used on the main thread since it already does async network calls so that's likely causing the issue. Can you add logging on your side for what thread you're in and run with the Integration version and send over the log file?

**Comment by milindjoshi297** [comment]
Hi @nuclearghost Thanks for the reply.

There are few scenarios we came across as follows,

1.If we integrate "SharethroughSDK.DFP.framework", then it shows ad on iPhone without any problem(Without disappearing ads issue), but it doesnot shows any ad on iPad using this framework.

2.As sharethrough developer suggested initially, we integrated "SharethroughSDK.DFP.Integration.framework", then it shows ad on iPhone and iPad both, but Ads are disappearing after few seconds of display. This scenario occurs on both the devices.

Error : "Native Ad MPPFeaturedNative did fail to receive ad: Error Domain=com.cheezburger.Cheezburger Code=10803 "(null)"" 

If we would have GCD problem then point 1 above would not work on iPhone, but Ads are showing on iPhone without any disappearing issue. So by considering this, there may be some different cause of the problem.

We are also verifying whether it does not run on main thread. So that we can provide you the details of the same.

Thanks !!!

**Comment by milindjoshi297** [comment]
Hi @nuclearghost 
As you suggested, we verified the code and while displaying the Ad it runs on "Main Queue" only. Please check the Log file attached herewith.

Is there any update from your side?

[iPadLog_OnMainThread.txt](https://github.com/sharethrough/iOS-SDK/files/231238/iPadLog_OnMainThread.txt)

Thanks

**Comment by nuclearghost** [comment]
Hi @milindjoshi297 

I notice that every time you call the Sharethrough SDK, the following error appears 
```
 <Warning>: [HTNativeAdAssetItemViewCell.m:250] __52-[HTNativeAdAssetItemViewCell reuseCellWithNativeAd]_block_invoke.153: Native Ad MPPFeaturedNative did fail to receive ad: Error Domain=com.cheezburger.Cheezburger Code=10803 "(null)"
```

Would it be possible to get read access to your repo? That would help me to reproduce more quickly.
