### ISSUE TITLE
adWasRenderedInView

### ISSUE THREAD

**Issue by cthomaschase** [sharethrough/iOS-SDK#32]
I see a note in the change log of version 3.2.5 about a new method `adWasRenderedInView` that's to be called when the ad is rendered. Do we need to call this if we're using the implementation 

```objective-c
- (void)placeAdInView:(UIView<STRAdView> *)view placementKey:(NSString *)placementKey presentingViewController:(UIViewController *)presentingViewController index:(NSInteger)index delegate:(id<STRAdViewDelegate>)delegate;
```

**Comment by nuclearghost** [comment]
@cthomaschase nope that's not necessary if you're using that API. It's only necessary when manually rendering the ad

**Comment by cthomaschase** [comment]
Thanks
